# Generated by Django 4.2.16 on 2025-05-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Image"),
                ),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name_plural": "Galleries",
            },
        ),
    ]
