# Generated by Django 4.2.16 on 2025-05-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="description",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="title",
        ),
    ]
